export const SAVE_VERSION=1;
export const ERA_IDS=['matter','cells','organisms','villages','civilizations','planets'];
export const ERAS=[
  {id:'matter',name:'First matter',chapter:'Bond a beginning',date:'≈ 4.5 billion years ago',scale:'Atoms → molecules',exponent:-10,minutes:4,palette:['#2b1e2a','#ffc966','#f38461'],camera:'float',history:'Earth formed around 4.5 billion years ago from material already present in the young solar system. Your seed and its magnetic powers are fantasy.',source:'https://science.nasa.gov/astrobiology/learning-resources/alp/sources-of-lifes-building-blocks/',names:['Hydrogen','Carbon','Oxygen','Nitrogen','Iron fragment','Silicate mineral','Water cluster','Methane cluster','Ammonia cluster'],roles:['H','C','O','N','mineral','mineral','H2O','CH4','NH3']},
  {id:'cells',name:'Living oceans',chapter:'Keep a little life alive',date:'Early life · billions of years ago',scale:'Micrometers → colonies',exponent:-6,minutes:6,palette:['#073c45','#76e4c5','#faac84'],camera:'fluid',history:'Evidence places life on Earth more than 3.5 billion years ago. Exactly how life began remains an open scientific question; the chapter is an imaginative model of membranes and cooperation.',source:'https://science.nasa.gov/astrobiology/learning-resources/alp/sources-of-lifes-building-blocks/',names:['Energy vesicle','Lipid droplet','Protein vesicle','Motion symbiont','Repair symbiont','Energy symbiont','Toxin','Membrane seed','Ancestral spark'],roles:['energy','lipid','protein','motion','repair','photosynthesis','toxin','seed','ancestor']},
  {id:'organisms',name:'A moving ecosystem',chapter:'Learn three ways to live',date:'Complex life · changing habitats',scale:'Millimeters → meters',exponent:0,minutes:7,palette:['#163d33','#dbdf82','#ee8973'],camera:'ground',history:'Complex life diversified across many branches and environments. This moving ecosystem combines swimming, land movement, and cold adaptation; it is not a literal evolutionary lineage.',source:'https://astrobiology.nasa.gov/news/how-did-multicellular-life-evolve/',names:['Fin fish','Shell snail','Amphibian','Furry mammal','Fern colony','Cold moss','Predator','Companion bird','Ecosystem seed'],roles:['swim','armor','land','insulation','flora','cold','predator','ally','seed']},
  {id:'villages',name:'Farming together',chapter:'Carry a thriving village',date:'≈ 12,000 years ago onward',scale:'Meters → settlements',exponent:2,minutes:7,palette:['#61432c','#f3d397','#9fc98b'],camera:'settlement',history:'Farming and herding developed in multiple regions. Food production and settlement changed landscapes and supported growing communities. Your moving village is a cooperative fantasy.',source:'https://humanorigins.si.edu/human-characteristics/humans-change-world',names:['Farm','Granary','Home','Workshop','Quarry','Woodland','Bridge','Well','Village raft'],roles:['farm','granary','home','workshop','quarry','forest','bridge','well','seed']},
  {id:'civilizations',name:'Connected worlds',chapter:'Make a civilization work',date:'Cities → industry → cooperation',scale:'Regions → a living planet',exponent:5,minutes:8,palette:['#233e56','#f9d988','#f18983'],camera:'network',history:'Cities and civilizations developed along many different paths. This chapter combines trade, energy, research, and cooperation across fictional regions, without presenting one culture as a universal destination.',source:'https://humanorigins.si.edu/human-characteristics/humans-change-world',names:['Terraced Highlands','River Cities','Woodland Coast','Wind hub','Trade port','Research hub','Orbital project','Rail hub','Living world'],roles:['city','city','city','energy','trade','research','rocket','transport','seed']},
  {id:'planets',name:'A living cosmos',chapter:'Carry your history into the stars',date:'Beyond the present · imagined future',scale:'Moons → planetary worlds',exponent:7,minutes:6,palette:['#121b3b','#b5a6ef','#72e5da'],camera:'orbit',history:'Planets existed long before human civilizations. This finale imagines a future in which your impossible seed carries Earth’s living history into a gravitationally bound collection of worlds.',source:'https://science.nasa.gov/solar-system/',names:['Asteroid','Cratered moon','Rocky world','Icy world','Gas giant','Living Earth','Orbit beacon','Biosphere crystal','Cosmic seed'],roles:['debris','moon','rocky','icy','gas','earth','beacon','energy','seed']},
];
export const PATHS={
  cohesion:{name:'Cohesion',tag:'A resilient living shell',color:'#f1b779',description:'Keep your structure steady when things get difficult.'},
  motion:{name:'Motion',tag:'An agile, restless body',color:'#99c9ff',description:'Move, travel, and change course more effectively.'},
  symbiosis:{name:'Symbiosis',tag:'A flourishing cooperative world',color:'#8de0b4',description:'Turn connections and living partners into useful resources.'},
};
export const BENEFITS={
  cells:{cohesion:'A recoverable membrane shield and better toxin tolerance.',motion:'An additional current-crossing burst.',symbiosis:'More useful nutrients and a cooperative recovery link.'},
  organisms:{cohesion:'A shell that can deflect a predator hit.',motion:'A stronger dash with a second stored burst.',symbiosis:'A companion that distracts approaching predators.'},
  villages:{cohesion:'Safer transport through river hazards.',motion:'Faster travel between resource destinations.',symbiosis:'More productive farms and cooperative supply links.'},
  civilizations:{cohesion:'More time to recover a failed essential route.',motion:'Faster goods transport and a free rapid reroute.',symbiosis:'Shared reserves support connected cities.'},
  planets:{cohesion:'A shield against a tidal-stress spike.',motion:'More effective thrust and an extra velocity burst.',symbiosis:'Habitable worlds help restore your fuel.'},
};
export function modifiers(build){return{tolerance:1+Math.min(.6,build.cohesion*.15),mobility:1+Math.min(.4,build.motion*.1),yield:1+Math.min(.6,build.symbiosis*.15),shield:build.cohesion>0,burst:build.motion>0,cooperate:build.symbiosis>0};}
export function randomSeed(seed){return()=>{seed|=0;seed=seed+0x6d2b79f5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function hash(...parts){let h=2166136261;for(const c of parts.join(':')){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function metric(logMeters){if(logMeters<-6)return`${(10**(logMeters+9)).toPrecision(2)} nm`;if(logMeters<-3)return`${(10**(logMeters+6)).toPrecision(2)} μm`;if(logMeters<0)return`${(10**(logMeters+3)).toPrecision(2)} mm`;if(logMeters<3)return`${(10**logMeters).toPrecision(3)} m`;return`${(10**(logMeters-3)).toPrecision(3)} km`;}
