import './style.css';
import * as THREE from 'three';
import {ERAS,PATHS,BENEFITS,clamp} from './config.js';
import {SaveStore} from './save.js';
import {CampaignController} from './campaign-controller.js';
import {ERA_MODULES} from './eras/index.js';
import {AssetLibrary} from './render/assets.js';
import {WorldRenderer} from './render/world.js';
import {initializePhysics} from './render/physics.js';
const app=document.querySelector('#app');
app.innerHTML='<canvas id="world" tabindex="0" aria-label="Eon Roll world"></canvas><header><b>EON <em>ROLL</em></b><nav><button id="journal">Journal</button><button id="sound">Sound off</button><button id="pause">Pause</button></nav></header><section id="hud" class="hidden"><small id="era"></small><h2 id="chapter"></h2><p id="objective"></p><div class="track"><i id="progress"></i></div><p id="resource"></p><div class="track thin"><i id="energy"></i></div><small id="timeline"></small></section><div id="toast" role="status"></div><div id="guide"></div><section id="controls" class="hidden"><div id="joystick" aria-label="Drag to steer"><span id="stick"></span><small>STEER</small></div><div class="control-right"><div id="actions"></div><small id="help"></small></div></section><section id="overlay"><article id="panel"><small>4.5 BILLION YEARS. ONE IMPOSSIBLE JOURNEY.</small><h1>EON<br><em>ROLL</em></h1><p>Gather the history of Earth into one living body.</p><p>Preparing your first worldâ€¦</p></article></section><div id="drag" class="hidden"></div>';
const $=id=>document.getElementById(id),store=new SaveStore(),campaign=new CampaignController(store),assets=new AssetLibrary(),keys=new Set(),joy={x:0,z:0,id:null};let world,module,saved,started=false,paused=true,busy=false,last=performance.now(),saveClock=0,hudClock=0,actionSig='',dragType=null,toastClock=0,inspector=null,inspectFrame=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let muted=localStorage.getItem('eon:sound')!=='on',audio,music;
function tone(freq=440,duration=.14){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.04,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function soundscape(){clearInterval(music);const notes=[[130,164,196],[146,220,293],[174,261,349],[196,246,293],[220,329,440],[130,196,261,392]][campaign.state.era];let i=0;music=setInterval(()=>{if(!paused&&!busy)tone(notes[i++%notes.length],1.8);},1500);}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastClock=performance.now()+4000;}
function panel(html){$('panel').innerHTML=html;$('overlay').classList.remove('hidden');}
function close(){ $('overlay').classList.add('hidden');}
function btn(text,fn,kind='primary'){const b=document.createElement('button');b.textContent=text;b.className=kind;b.onclick=()=>Promise.resolve(fn()).catch(fatal);return b;}
function save(checkpoint=false){if(module&&started)campaign.saveEra(module,checkpoint);}
function pause(){paused=true;keys.clear();joy.x=joy.z=0;$('stick').style.transform='none';save();}
function actions(){const available=[...module.actions,...(module.id==='villages'?module.entities.filter(e=>e.interactive).map(e=>({id:'visit:'+e.id,label:e.name})):module.id==='civilizations'?module.entities.filter(e=>e.role==='city').map(e=>({id:'visit:'+e.id,label:e.name})):[])];const sig=available.map(a=>a.id+a.label).join('|');if(sig===actionSig)return;actionSig=sig;$('actions').replaceChildren();available.forEach(a=>{const b=document.createElement('button');b.innerHTML=a.label+'<small>'+(a.build?'DRAG / SELECT':a.key?.replace('Key','').replace('Digit','')||'TAP')+'</small>';b.title=a.hint||'Select then tap a plot';b.onpointerdown=e=>{e.preventDefault();if(a.id.startsWith('visit:'))module.select(a.id.slice(6));else module.action(a.id,true);tone(330);if(a.build){dragType=a.id;$('drag').textContent=a.label;$('drag').classList.remove('hidden');moveDrag(e);b.setPointerCapture(e.pointerId);}else if(a.hold)b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(a.build&&dragType)moveDrag(e);};b.onpointerup=e=>{if(a.hold)module.action(a.id,false);if(a.build&&dragType){const p=world.pick(e.clientX,e.clientY);if(p?.slot!==undefined)module.build(dragType,p.slot);dragType=null;$('drag').classList.add('hidden');}hud();};b.onpointercancel=()=>{if(a.hold)module.action(a.id,false);dragType=null;$('drag').classList.add('hidden');};$('actions').append(b);});}
function moveDrag(e){$('drag').style.left=e.clientX+'px';$('drag').style.top=e.clientY+'px';}
function hud(){if(!module)return;const meta=module.meta,r=module.resource;document.documentElement.style.setProperty('--accent',meta.palette[1]);$('era').textContent=(module.index+1)+' / 6 Â· '+meta.name;$('chapter').textContent=meta.chapter;$('objective').textContent=module.objective;$('progress').style.width=clamp(module.progress*100,0,100)+'%';$('resource').textContent=r.label+' Â· '+r.value;$('energy').style.width=clamp(r.value/r.max*100,0,100)+'%';$('timeline').textContent=campaign.state.timeline;actions();const mode=module.viewConfig.mode;$('joystick').classList.toggle('hidden',mode!=='move');$('help').textContent=mode==='route'?'Tap destinations Â· Drag buildings onto connected plots':mode==='network'?'Tap city pairs to connect Â· Select city, then build':module.id==='planets'?'Thrust with stick Â· Brake Â· Match velocity to bind':'Steer with stick or WASD Â· Esc pauses';const goal=module.viewConfig.goal;$('guide').textContent=goal?'Destination: '+goal.name+' Â· '+Math.round(Math.hypot(goal.x-module.state.x,goal.z-module.state.z))+' away':'';}
async function enter(){busy=true;actionSig='';world.zoomMultiplier=1;const meta=ERAS[campaign.state.era];panel('<small>'+meta.date+'</small><h2>'+meta.name+'</h2><p>'+meta.chapter+'</p><p>Your earlier history stays inside you.</p><div class="loader"></div>');await assets.loadEra(meta.id);if(meta.id==='organisms')await initializePhysics();module=new ERA_MODULES[campaign.state.era](campaign);module.enter(campaign.state.eraStates[meta.id]);module.createRenderer(world);
if(meta.id==='villages')for(const b of module.state.buildings){const kind={farm:0,home:2,granary:1,workshop:3,bridge:6,well:7}[b.type],s=module.slots[b.slot];if(!campaign.has('building-'+b.slot))module.collect({id:'building-'+b.slot,kind,name:meta.names[kind],role:b.type},{position:[s.x,1.5,s.z],dimensions:[2,2,1],rotation:[0,0,0,1],fixed:true});}
if(meta.id==='civilizations')for(const city of module.entities.filter(e=>e.role==='city'))if(!campaign.has(city.id))module.collect(city,{position:[city.x,3.5,city.z],dimensions:[7,7,3],fixed:true});
busy=false;paused=false;close();$('hud').classList.remove('hidden');$('controls').classList.remove('hidden');hud();soundscape();if(campaign.state.status==='adaptation')adapt();else if(campaign.state.status==='finished')finish();else{campaign.beginEra();save(true);}if(campaign.state.era<5)assets.loadEra(ERAS[campaign.state.era+1].id).catch(()=>{});}
async function start(fresh){started=true;if(fresh)campaign.newRun();else if(saved)campaign.restore(saved);await enter();}
function title(){panel('<small>A SMALL BEGINNING. AN IMPOSSIBLE JOURNEY.</small><h1>EON<br><em>ROLL</em></h1><p class="intro">Gather the history of Earth into one living, growing body.</p><div class="preview">'+ERAS.map(e=>'<figure><img src="/eon/'+e.id+'/8.webp" alt="'+e.name+'"><figcaption>'+e.name+'</figcaption></figure>').join('')+'</div><p class="subtle">Six changing ways to play. One persistent entity.<br>A finite adventure with automatic local saves.</p><div id="menu-buttons" class="stack"></div>');if(saved)$('menu-buttons').append(btn(saved.status==='finished'?'View your completed cosmos':'Resume Â· '+ERAS[saved.era].name,()=>start(false)));$('menu-buttons').append(btn(saved?'Begin a new history':'Begin your journey',()=>start(true),saved?'secondary':'primary'));if(store.profile.completed)$('menu-buttons').append(btn('Choose a chapter',chapters,'secondary'));}
function adapt(){pause();$('controls').classList.add('hidden');const next=ERAS[campaign.state.era+1];panel('<small>'+module.meta.name+' COMPLETE</small><h2>What will you<br><em>become?</em></h2><p>Choose an adaptation for '+next.name.toLowerCase()+'.</p><div id="choices" class="stack"></div>');for(const[path,spec]of Object.entries(PATHS)){const b=btn('',()=>campaign.choose(path),'choice');b.style.borderColor=spec.color;b.innerHTML='<strong style="color:'+spec.color+'">'+spec.name+' <small>RANK '+(campaign.state.build[path]+1)+'</small></strong><span>'+BENEFITS[next.id][path]+'</span>';$('choices').append(b);}tone(660,.8);}
function pauseScreen(){if(!started||busy)return;pause();panel('<small>YOUR HISTORY IS SAVED</small><h2>Take a breath.</h2><p>'+module.meta.name+' Â· '+campaign.state.ledger.length+' objects retained.</p><div id="pause-buttons" class="stack"></div><p class="subtle">Saved on this device. Resume inside this chapter.</p>');$('pause-buttons').append(btn('Keep going',()=>{paused=false;close();}),btn('History & collection',()=>journal(),'secondary'),btn('Return to safe checkpoint',()=>{campaign.recovery(module,'Checkpoint restored. Your collected history remains.');paused=false;close();},'secondary'));}
function journal(final=false){pause();panel('<small>THE HISTORY YOU CARRY</small><h2>Your living archive.</h2><div id="history"></div><div id="back" class="stack"></div>');for(const [i,e]of ERAS.entries()){const records=campaign.state.ledger.filter(r=>r.era===i),section=document.createElement('section');section.className='history-era';section.innerHTML='<strong>'+i+' Â· '+e.name+'</strong><p>'+e.history+'</p><a href="'+e.source+'" target="_blank" rel="noopener noreferrer">Historical context â†—</a><div class="discoveries">'+Object.values(store.profile.discoveries).filter(d=>d.eraId===e.id).map(d=>'<figure><img src="/eon/'+e.id+'/'+d.assetKey.split(':')[1]+'.webp" alt="'+d.name+'"><figcaption>'+d.name+'</figcaption></figure>').join('')+'</div>';if(records.length)section.append(btn('Inspect '+records.length+' persistent objects',()=>inspect(i,()=>journal(final)),'secondary'));$('history').append(section);}$('back').append(btn(final?'Back to your cosmos':'Keep going',()=>{if(final)finish();else{paused=false;close();}}));}
async function inspect(index,back){const era=ERAS[index];panel('<small>LAYER '+(index+1)+' Â· '+era.scale+'</small><h2>'+era.name+'</h2><canvas id="layer"></canvas><p id="layer-info" class="subtle">Reconstructing saved historyâ€¦</p><div id="layer-back" class="stack"></div>');await assets.loadEra(era.id);const canvas=$('layer');if(!canvas)return;inspector=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});inspector.setPixelRatio(Math.min(devicePixelRatio,2));const scene=new THREE.Scene(),body=new THREE.Group();scene.add(body,new THREE.HemisphereLight('#fff8e9','#706289',2));const light=new THREE.DirectionalLight('#fff5dd',2);light.position.set(5,10,12);scene.add(light);const core=assets.model(index===0?'cells:8':era.id+':8');body.add(new THREE.Mesh(core.geometry,core.material));const records=campaign.state.ledger.filter(r=>r.era===index);for(const r of records){const model=assets.model(r.assetKey),t=r.relativeTransform;if(!model||!t.position)continue;const mesh=new THREE.Mesh(model.geometry,model.material),d=t.dimensions||[2,2,2];mesh.position.fromArray(t.position);mesh.quaternion.fromArray(t.rotation||[0,0,0,1]);mesh.scale.set(d[0]/Math.max(.01,model.ratio),d[1],d[2]/Math.max(.01,model.depth));body.add(mesh);}const box=new THREE.Box3().setFromObject(body),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=Math.max(...size.toArray(),3);body.position.sub(center);const camera=new THREE.PerspectiveCamera(40,1,.01,1000);camera.position.set(radius*.8,radius*.6,radius*1.8);camera.lookAt(0,0,0);$('layer-info').textContent=records.length+' persistent objects Â· local scale 10^'+era.exponent+' meters Â· trace back to the microscopic core';let angle=0;function draw(){if(!inspector)return;inspector.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/Math.max(1,canvas.clientHeight);camera.updateProjectionMatrix();if(!reduced)angle+=.003;body.rotation.y=angle;inspector.render(scene,camera);inspectFrame=requestAnimationFrame(draw);}draw();canvas.onpointerdown=()=>{angle+=.4;};$('layer-back').append(btn('Back to archive',()=>{cancelAnimationFrame(inspectFrame);inspector.dispose();inspector=null;back();}));}
function finish(){pause();world.zoomMultiplier=reduced?1:2.1;$('controls').classList.add('hidden');panel('<small>FROM FIRST MATTER TO A LIVING COSMOS</small><h2>You carried<br><em>everything.</em></h2><img class="final-art" src="/eon/planets/8.webp" alt="A living cosmos"><p>'+campaign.state.ledger.length+' objects. Six eras. One history.</p><div class="build-summary">'+Object.entries(PATHS).map(([p,s])=>'<span>'+s.name+'<strong>'+campaign.state.build[p]+'</strong></span>').join('')+'</div><p class="subtle">Your original microscopic core remains inside the layers.<br>The journey has an end. Your discoveries remain.</p><div id="final-buttons" class="stack"></div>');$('final-buttons').append(btn('Reveal your layers',()=>journal(true)),btn('Replay with a different build',()=>start(true),'secondary'),btn('Choose a chapter',chapters,'secondary'));tone(783,1.2);}
function chapters(){pause();panel('<small>COMPLETED CAMPAIGN Â· CHAPTERS UNLOCKED</small><h2>A different way<br>through history.</h2><div id="chapter-buttons" class="stack"></div>');ERAS.forEach((e,i)=>$('chapter-buttons').append(btn((i+1)+' Â· '+e.name,()=>{campaign.newRun();campaign.state.era=i;for(let n=0;n<i;n++)campaign.state.build[['cohesion','motion','symbiosis'][n%3]]++;started=true;return enter();},'choice')));$('chapter-buttons').append(btn('Back',()=>started?finish():title(),'secondary'));}
function fatal(e){busy=false;paused=true;console.error(e);panel('<small>WORLD LOADING INTERRUPTED</small><h2>Your save is safe.</h2><p>'+String(e.message||e).replace(/[<>]/g,'')+'</p><div id="reload" class="stack"></div>');$('reload').append(btn('Reload this world',()=>location.reload()));}
campaign.onEvent(e=>{if(e.type==='collection'){world?.current?.collect(e.record);tone(280+campaign.state.ledger.length%8*55);toast(e.record.name+' Â· part of you');}if(['feedback','checkpoint','recovery'].includes(e.type)){toast(e.message);if(e.type==='recovery')world?.current?.recover();}if(e.type==='adaptation')adapt();if(e.type==='finished')finish();if(e.type==='transition'){busy=true;pause();tone(523,.8);setTimeout(()=>enter().catch(fatal),reduced?0:1800);}});
function updateJoy(e){const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),limit=r.width*.32;joy.x=dx/Math.max(limit,len);joy.z=dz/Math.max(limit,len);$('stick').style.transform='translate('+joy.x*limit+'px,'+joy.z*limit+'px)';}
$('joystick').onpointerdown=e=>{if(paused)return;e.preventDefault();joy.id=e.pointerId;$('joystick').setPointerCapture(e.pointerId);updateJoy(e);};$('joystick').onpointermove=e=>{if(e.pointerId===joy.id)updateJoy(e);};for(const t of ['pointerup','pointercancel'])$('joystick').addEventListener(t,()=>{joy.id=null;joy.x=joy.z=0;$('stick').style.transform='none';});
let pointer;$('world').onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY};};$('world').onpointerup=e=>{if(paused||!module||!pointer||Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>12)return;const pick=world.pick(e.clientX,e.clientY);if(pick?.entity)module.select(pick.entity);if(pick?.slot!==undefined)module.build(module.state.selected,pick.slot);hud();};
addEventListener('keydown',e=>{if(e.code==='Escape'){if(paused&&$('pause-buttons')){paused=false;close();}else pauseScreen();return;}if(paused||!module)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!keys.has(e.code)){const a=module.actions.find(a=>a.key===e.code);if(a)module.action(a.id,true);else if(module.id==='villages'&&/^Digit[1-6]$/.test(e.code))module.action(module.actions[Number(e.code.slice(-1))-1]?.id);}keys.add(e.code);});addEventListener('keyup',e=>{keys.delete(e.code);const a=module?.actions.find(a=>a.key===e.code&&a.hold);if(a)module.action(a.id,false);});
$('pause').onclick=pauseScreen;$('journal').onclick=()=>started?journal(campaign.state.status==='finished'):toast('Begin your journey to build your collection.');$('sound').onclick=()=>{muted=!muted;localStorage.setItem('eon:sound',muted?'off':'on');$('sound').textContent=muted?'Sound off':'Sound on';tone(523,.25);};$('sound').textContent=muted?'Sound off':'Sound on';addEventListener('resize',()=>world?.resize());document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!busy)pauseScreen();});addEventListener('blur',()=>{if(started&&!paused&&!busy)pauseScreen();});addEventListener('pagehide',()=>save(true));
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.033,(now-last)/1000);last=now;if(module&&started&&!paused&&!busy&&campaign.state.status==='playing'){let x=joy.x+Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),z=joy.z+Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'));const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}module.update(dt,{x,z});campaign.state.elapsed+=dt;saveClock+=dt;hudClock+=dt;if(saveClock>=4){save();saveClock=0;}if(hudClock>=.15){hud();hudClock=0;}}if(world?.current)world.update(paused||busy?0:dt);if(now>toastClock)$('toast').classList.remove('visible');}
async function boot(){await Promise.all([store.open(),assets.init()]);saved=await store.load();if(saved)campaign.restore(saved);else campaign.newRun();await assets.loadEra('matter');world=new WorldRenderer($('world'),assets);new ERA_MODULES[0](campaign).createRenderer(world);title();requestAnimationFrame(frame);}boot().catch(fatal);
